// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.3.6.0
// Schema file: config.xsd
// Creation Date: 14/02/2005 4:55:16 PM
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace com.csiro.xml.datatype
{

	public struct Declarations
	{
		public const string SchemaVersion = "1.0.0";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class PropertyCollection : ArrayList
	{
		public Property Add(Property obj)
		{
			base.Add(obj);
			return obj;
		}

		public Property Add()
		{
			return Add(new Property());
		}

		public void Insert(int index, Property obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(Property obj)
		{
			base.Remove(obj);
		}

		new public Property this[int index]
		{
			get { return (Property) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class CatelogCollection : ArrayList
	{
		public Catelog Add(Catelog obj)
		{
			base.Add(obj);
			return obj;
		}

		public Catelog Add()
		{
			return Add(new Catelog());
		}

		public void Insert(int index, Catelog obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(Catelog obj)
		{
			base.Remove(obj);
		}

		new public Catelog this[int index]
		{
			get { return (Catelog) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class ItemCollection : ArrayList
	{
		public Item Add(Item obj)
		{
			base.Add(obj);
			return obj;
		}

		public Item Add()
		{
			return Add(new Item());
		}

		public void Insert(int index, Item obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(Item obj)
		{
			base.Remove(obj);
		}

		new public Item this[int index]
		{
			get { return (Item) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlRoot(ElementName="Config",IsNullable=false),Serializable]
	public class Config
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
			return CatelogCollection.GetEnumerator();
		}

		public Catelog Add(Catelog obj)
		{
			return CatelogCollection.Add(obj);
		}

		[XmlIgnore]
		public Catelog this[int index]
		{
			get { return (Catelog) CatelogCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return CatelogCollection.Count; }
        }

        public void Clear()
		{
            CatelogCollection.Clear();
        }

		public Catelog Remove(int index) 
		{ 
            Catelog obj = CatelogCollection[index];
            CatelogCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            CatelogCollection.Remove(obj);
        }

		[XmlAttribute(AttributeName="name",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlAttribute(AttributeName="type",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __type;
		
		[XmlIgnore]
		public string type
		{ 
			get { return __type; }
			set { __type = value; }
		}

		[XmlAttribute(AttributeName="note",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __note;
		
		[XmlIgnore]
		public string note
		{ 
			get { return __note; }
			set { __note = value; }
		}

		[XmlElement(Type=typeof(Catelog),ElementName="Catelog",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CatelogCollection __CatelogCollection;
		
		[XmlIgnore]
		public CatelogCollection CatelogCollection
		{
			get
			{
				if (__CatelogCollection == null) __CatelogCollection = new CatelogCollection();
				return __CatelogCollection;
			}
			set {__CatelogCollection = value;}
		}

		public Config()
		{
		}
	}


	[XmlType(TypeName="Catelog"),XmlRoot,Serializable]
	public class Catelog
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
			return ItemCollection.GetEnumerator();
		}

		public Item Add(Item obj)
		{
			return ItemCollection.Add(obj);
		}

		[XmlIgnore]
		public Item this[int index]
		{
			get { return (Item) ItemCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return ItemCollection.Count; }
        }

        public void Clear()
		{
            ItemCollection.Clear();
        }

		public Item Remove(int index) 
		{ 
            Item obj = ItemCollection[index];
            ItemCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            ItemCollection.Remove(obj);
        }

		[XmlAttribute(AttributeName="name",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlAttribute(AttributeName="type",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __type;
		
		[XmlIgnore]
		public string type
		{ 
			get { return __type; }
			set { __type = value; }
		}

		[XmlAttribute(AttributeName="note",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __note;
		
		[XmlIgnore]
		public string note
		{ 
			get { return __note; }
			set { __note = value; }
		}

		[XmlElement(Type=typeof(Item),ElementName="Item",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ItemCollection __ItemCollection;
		
		[XmlIgnore]
		public ItemCollection ItemCollection
		{
			get
			{
				if (__ItemCollection == null) __ItemCollection = new ItemCollection();
				return __ItemCollection;
			}
			set {__ItemCollection = value;}
		}

		public Catelog()
		{
		}
	}


	[XmlType(TypeName="Item"),XmlRoot,Serializable]
	public class Item
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
			return PropertyCollection.GetEnumerator();
		}

		public Property Add(Property obj)
		{
			return PropertyCollection.Add(obj);
		}
/*
		[XmlIgnore]
		public Property this[int index]
		{
			get { return (Property) PropertyCollection[index]; }
		}
*/
		[XmlIgnore]
        public int Count 
		{
            get { return PropertyCollection.Count; }
        }

        public void Clear()
		{
            PropertyCollection.Clear();
        }

		public Property Remove(int index) 
		{ 
            Property obj = PropertyCollection[index];
            PropertyCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            PropertyCollection.Remove(obj);
        }

		[XmlAttribute(AttributeName="name",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlAttribute(AttributeName="type",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __type;
		
		[XmlIgnore]
		public string type
		{ 
			get { return __type; }
			set { __type = value; }
		}

		[XmlAttribute(AttributeName="note",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __note;
		
		[XmlIgnore]
		public string note
		{ 
			get { return __note; }
			set { __note = value; }
		}

		[XmlElement(Type=typeof(Property),ElementName="Property",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public PropertyCollection __PropertyCollection;
		
		[XmlIgnore]
		public PropertyCollection PropertyCollection
		{
			get
			{
				if (__PropertyCollection == null) __PropertyCollection = new PropertyCollection();
				return __PropertyCollection;
			}
			set {__PropertyCollection = value;}
		}

		public Item()
		{
		}
	}


	[XmlType(TypeName="Property"),XmlRoot,Serializable]
	public class Property
	{

		[XmlAttribute(AttributeName="name",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __name;
		
		[XmlIgnore]
		public string name
		{ 
			get { return __name; }
			set { __name = value; }
		}

		[XmlAttribute(AttributeName="value",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __value;
		
		[XmlIgnore]
		public string @value
		{ 
			get { return __value; }
			set { __value = value; }
		}

		[XmlAttribute(AttributeName="note",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __note;
		
		[XmlIgnore]
		public string note
		{ 
			get { return __note; }
			set { __note = value; }
		}

		public Property()
		{
		}
	}
}
